version: '3'

services: 
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=dontforget
      - POSTGRESQL_PASSWORD=dontforget
      - POSTGRESQL_DATABASE=dont-forget-db