version: '3'

services: 
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=dontforget
      - POSTGRESQL_PASSWORD=dontforget
      - POSTGRESQL_DATABASE=dont-forget-db

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dfUser
      - MONGO_INITDB_ROOT_PASSWORD=dfPassword

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dfUser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dfPassword
      - ME_CONFIG_MONGODB_URL=mongodb://dfUser:dfPassword@mongo:27017/